### ISSUE TITLE
Non-deterministic 'DataManager' object has no attribute 'storage_access'

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#809]
Sometimes when creating `File`s with Globus URLs, the creation fails with the below exception. This is non-deterministic, and I expect it is based on non-deterministic order at which `_get_globus_endpoint()` iterates over executors.

I think this was introduced by PR #805, which changes the list of executors used by the data manager, to now include itself as an executor.

```
  File "parsl/tests/test_staging/test_implicit_staging_globus.py", line 29, in test_implicit_staging_globus
    unsorted_file = File('globus://03d7d06a-cb6b-11e8-8c6a-0a1d4c5c824a/unsorted.txt')
  File "/home/benc/parsl/src/parsl/parsl/data_provider/files.py", line 53, in __init__
    self.dman.add_file(self)
  File "/home/benc/parsl/src/parsl/parsl/data_provider/data_manager.py", line 112, in add_file
    self._set_local_path(file)
  File "/home/benc/parsl/src/parsl/parsl/data_provider/data_manager.py", line 115, in _set_local_path
    globus_ep = self._get_globus_endpoint()
  File "/home/benc/parsl/src/parsl/parsl/data_provider/data_manager.py", line 121, in _get_globus_endpoint
    for scheme in executor.storage_access:
AttributeError: 'DataManager' object has no attribute 'storage_access'
```

**Comment by benclifford** [comment]
fixed by #815
